"""
SAHAYAK Database Package
Exposes database connections, configuration constants, Pydantic data contracts, and CRUD helpers.
"""

from .config import (
    MONGODB_URI,
    MONGO_DB_NAME,
    COLLECTION_USERS,
    COLLECTION_CITIZEN_PROFILES,
    COLLECTION_SCHEMES,
    COLLECTION_SCHEME_RULES,
    COLLECTION_ELIGIBILITY_CHECKS,
    COLLECTION_CONVERSATIONS,
    COLLECTION_GRIEVANCES,
    COLLECTION_GRIEVANCE_UPDATES,
    COLLECTION_AUDIT_LOGS,
    get_db_settings,
)
from .connection import (
    get_async_client,
    get_async_db,
    get_sync_client,
    get_sync_db,
    get_db,
    ping_database,
    close_connections,
)
from .schemas import (
    UserRole,
    UserCreate,
    UserInDB,
    UserResponse,
    CitizenProfileCreate,
    CitizenProfileInDB,
    RuleCondition,
    SchemeRuleModel,
    SchemeCreate,
    SchemeInDB,
    CriteriaResult,
    EligibilityCheckRecord,
    GrievancePriority,
    GrievanceStatus,
    GrievanceCreate,
    GrievanceInDB,
    GrievanceUpdateRecord,
    AuditLogRecord,
)

__all__ = [
    "MONGODB_URI",
    "MONGO_DB_NAME",
    "COLLECTION_USERS",
    "COLLECTION_CITIZEN_PROFILES",
    "COLLECTION_SCHEMES",
    "COLLECTION_SCHEME_RULES",
    "COLLECTION_ELIGIBILITY_CHECKS",
    "COLLECTION_CONVERSATIONS",
    "COLLECTION_GRIEVANCES",
    "COLLECTION_GRIEVANCE_UPDATES",
    "COLLECTION_AUDIT_LOGS",
    "get_db_settings",
    "get_async_client",
    "get_async_db",
    "get_sync_client",
    "get_sync_db",
    "get_db",
    "ping_database",
    "close_connections",
    "UserRole",
    "UserCreate",
    "UserInDB",
    "UserResponse",
    "CitizenProfileCreate",
    "CitizenProfileInDB",
    "RuleCondition",
    "SchemeRuleModel",
    "SchemeCreate",
    "SchemeInDB",
    "CriteriaResult",
    "EligibilityCheckRecord",
    "GrievancePriority",
    "GrievanceStatus",
    "GrievanceCreate",
    "GrievanceInDB",
    "GrievanceUpdateRecord",
    "AuditLogRecord",
]
